spring.application.name=iot

spring.data.mongodb.uri=mongodb://localhost:27017/IoT

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=1000GB
spring.servlet.multipart.max-request-size=1000GB